input_data:
    q1_dataset: '../data/raw/judicial_autonomy_q1_dataset_09122024.csv'
    q2_dataset: '../data/raw/judicial_autonomy_q2_dataset_09122024.csv'

output_data:
    q1_dataset: '../data/clean/judicial_autonomy_q1_clean.csv'
    q2_dataset: '../data/clean/judicial_autonomy_q2_clean.csv'

    q1_output_index_macro: '../data/clean/judicial_autonomy_q1_index_macro.csv'
    q1_output_index_macro_micro: '../data/clean/judicial_autonomy_q1_index_macro_micro.csv'
    q1_output_index_macro_micro_add_info: '../data/clean/judicial_autonomy_q1_index_macro_micro_add_info.csv'

    # q1_appointment_actors_dataset: '../data/clean/q1_appointment_actors_clean.csv'
    # q1_appointment_criteria_dataset: '../data/clean/q1_appointment_criteria_clean.csv'
    # q1_appointment_transparency_dataset: '../data/clean/q1_appointment_transparency_clean.csv'
    # q1_judge_tenure_dataset: '../data/clean/q1_judge_tenure_clean.csv'
    # q1_judge_immunity_dataset: '../data/clean/q1_judge_immunity_clean.csv'
    # q1_judge_salary_dataset: '../data/clean/q1_judge_salary_clean.csv'
    # q1_disciplinary_proceedings_dataset: '../data/clean/q1_disciplinary_proceedings_clean.csv'
    # q1_conflict_recusal_evaluation_dataset: '../data/clean/q1_conflict_recusal_evaluation_clean.csv'
    # q1_judicial_self_governance_dataset: '../data/clean/q1_judicial_self_governance_clean.csv'
    # q1_courts_administration_dataset: '../data/clean/q1_courts_administration_clean.csv'